### ISSUE TITLE
Road to 1.0

### ISSUE THREAD

**Issue by ngtw-j** [ngtw-j/kn-func-lang#1]
- [ ] Add tests
- [x] Modify HTTP to show HTTP Request handler function
- [x] Moddify CloudEvents to use a CloudEvent handler function
- [x] Cleanup json files
- [ ] Test CloudEvents with PingSource

**Comment by ngtw-j** [comment]
binary will not be supported, unless someone wants to help me figure out or there is a clear use case for it
